
/* File generated by gen_cfile.py. Should not be modified. */

#include "gk.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Global_Interrupt_Enable_Digital = 0x1;		/* Mapped at index 0x6005, subindex 0x00 */
UNS16 Read_Inputs_16_Bit[] =		/* Mapped at index 0x6100, subindex 0x01 - 0x01 */
  {
    0xFFFF	/* 65535 */
  };
UNS16 Polarity_Input_16_Bit[] =		/* Mapped at index 0x6102, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS16 Filter_Constant_Input_16_Bit[] =		/* Mapped at index 0x6103, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS16 Interrupt_Mask_Any_Change_16_Bit[] =		/* Mapped at index 0x6106, subindex 0x01 - 0x01 */
  {
    0xFFFF	/* 65535 */
  };
UNS16 Interrupt_Mask_Low_to_High_16_Bit[] =		/* Mapped at index 0x6107, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS16 Interrupt_Mask_High_to_Low_16_Bit[] =		/* Mapped at index 0x6108, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS16 Write_Outputs_16_Bit[] =		/* Mapped at index 0x6300, subindex 0x01 - 0x01 */
  {
    0xFFFF	/* 65535 */
  };
UNS16 Change_Polarity_Outputs_16_Bit[] =		/* Mapped at index 0x6302, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS16 Error_Mode_Outputs_16_Bit[] =		/* Mapped at index 0x6306, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS16 Error_Value_Outputs_16_Bit[] =		/* Mapped at index 0x6307, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 gk_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 gk_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 gk_iam_a_slave = 1;

TIMER_HANDLE gk_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 gk_obj1000 = 0x0;	/* 0 */
                    subindex gk_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&gk_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 gk_obj1001 = 0x0;	/* 0 */
                    subindex gk_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 gk_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 gk_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t gk_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex gk_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&gk_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 gk_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 gk_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 gk_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 gk_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 gk_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 gk_highestSubIndex_obj1016 = 0;
                    UNS32 gk_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 gk_obj1017 = 0x3E8;	/* 1000 */
                    ODCallback_t gk_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex gk_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 gk_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 gk_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 gk_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 gk_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 gk_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex gk_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&gk_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&gk_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&gk_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&gk_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 gk_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 gk_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 gk_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex gk_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&gk_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&gk_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 gk_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 gk_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 gk_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 gk_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 gk_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 gk_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 gk_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex gk_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 gk_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 gk_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 gk_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 gk_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 gk_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 gk_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 gk_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex gk_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 gk_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 gk_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 gk_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 gk_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 gk_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 gk_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 gk_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex gk_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 gk_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 gk_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 gk_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 gk_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 gk_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 gk_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 gk_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex gk_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 gk_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 gk_obj1600[] = 
                    {
                      0x63000110,	/* 1660944656 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex gk_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 gk_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 gk_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex gk_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 gk_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 gk_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex gk_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 gk_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 gk_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex gk_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 gk_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 gk_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 gk_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 gk_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 gk_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 gk_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 gk_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t gk_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex gk_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 gk_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 gk_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 gk_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 gk_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 gk_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 gk_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 gk_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t gk_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex gk_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 gk_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 gk_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 gk_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 gk_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 gk_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 gk_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 gk_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t gk_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex gk_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 gk_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 gk_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 gk_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 gk_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 gk_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 gk_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 gk_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t gk_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex gk_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&gk_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&gk_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 gk_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 gk_obj1A00[] = 
                    {
                      0x61000110,	/* 1627390224 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex gk_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A00[7] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 gk_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 gk_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex gk_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 gk_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 gk_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex gk_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 gk_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 gk_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex gk_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&gk_obj1A03[7] }
                     };

/* index 0x6005 :   Mapped variable Global Interrupt Enable Digital */
                    subindex gk_Index6005[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&Global_Interrupt_Enable_Digital }
                     };

/* index 0x6100 :   Mapped variable Read Inputs 16 Bit */
                    UNS8 gk_highestSubIndex_obj6100 = 1; /* number of subindex - 1*/
                    subindex gk_Index6100[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6100 },
                       { RO, uint16, sizeof (UNS16), (void*)&Read_Inputs_16_Bit[0] }
                     };

/* index 0x6102 :   Mapped variable Polarity Input 16 Bit */
                    UNS8 gk_highestSubIndex_obj6102 = 1; /* number of subindex - 1*/
                    subindex gk_Index6102[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6102 },
                       { RW, uint16, sizeof (UNS16), (void*)&Polarity_Input_16_Bit[0] }
                     };

/* index 0x6103 :   Mapped variable Filter Constant Input 16 Bit */
                    UNS8 gk_highestSubIndex_obj6103 = 1; /* number of subindex - 1*/
                    subindex gk_Index6103[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6103 },
                       { RW, uint16, sizeof (UNS16), (void*)&Filter_Constant_Input_16_Bit[0] }
                     };

/* index 0x6106 :   Mapped variable Interrupt Mask Any Change 16 Bit */
                    UNS8 gk_highestSubIndex_obj6106 = 1; /* number of subindex - 1*/
                    subindex gk_Index6106[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6106 },
                       { RW, uint16, sizeof (UNS16), (void*)&Interrupt_Mask_Any_Change_16_Bit[0] }
                     };

/* index 0x6107 :   Mapped variable Interrupt Mask Low to High 16 Bit */
                    UNS8 gk_highestSubIndex_obj6107 = 1; /* number of subindex - 1*/
                    subindex gk_Index6107[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6107 },
                       { RW, uint16, sizeof (UNS16), (void*)&Interrupt_Mask_Low_to_High_16_Bit[0] }
                     };

/* index 0x6108 :   Mapped variable Interrupt Mask High to Low 16 Bit */
                    UNS8 gk_highestSubIndex_obj6108 = 1; /* number of subindex - 1*/
                    subindex gk_Index6108[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6108 },
                       { RW, uint16, sizeof (UNS16), (void*)&Interrupt_Mask_High_to_Low_16_Bit[0] }
                     };

/* index 0x6300 :   Mapped variable Write Outputs 16 Bit */
                    UNS8 gk_highestSubIndex_obj6300 = 1; /* number of subindex - 1*/
                    subindex gk_Index6300[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6300 },
                       { RW, uint16, sizeof (UNS16), (void*)&Write_Outputs_16_Bit[0] }
                     };

/* index 0x6302 :   Mapped variable Change Polarity Outputs 16 Bit */
                    UNS8 gk_highestSubIndex_obj6302 = 1; /* number of subindex - 1*/
                    subindex gk_Index6302[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6302 },
                       { RW, uint16, sizeof (UNS16), (void*)&Change_Polarity_Outputs_16_Bit[0] }
                     };

/* index 0x6306 :   Mapped variable Error Mode Outputs 16 Bit */
                    UNS8 gk_highestSubIndex_obj6306 = 1; /* number of subindex - 1*/
                    subindex gk_Index6306[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6306 },
                       { RW, uint16, sizeof (UNS16), (void*)&Error_Mode_Outputs_16_Bit[0] }
                     };

/* index 0x6307 :   Mapped variable Error Value Outputs 16 Bit */
                    UNS8 gk_highestSubIndex_obj6307 = 1; /* number of subindex - 1*/
                    subindex gk_Index6307[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&gk_highestSubIndex_obj6307 },
                       { RW, uint16, sizeof (UNS16), (void*)&Error_Value_Outputs_16_Bit[0] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable gk_objdict[] = 
{
  { (subindex*)gk_Index1000,sizeof(gk_Index1000)/sizeof(gk_Index1000[0]), 0x1000},
  { (subindex*)gk_Index1001,sizeof(gk_Index1001)/sizeof(gk_Index1001[0]), 0x1001},
  { (subindex*)gk_Index1017,sizeof(gk_Index1017)/sizeof(gk_Index1017[0]), 0x1017},
  { (subindex*)gk_Index1018,sizeof(gk_Index1018)/sizeof(gk_Index1018[0]), 0x1018},
  { (subindex*)gk_Index1200,sizeof(gk_Index1200)/sizeof(gk_Index1200[0]), 0x1200},
  { (subindex*)gk_Index1400,sizeof(gk_Index1400)/sizeof(gk_Index1400[0]), 0x1400},
  { (subindex*)gk_Index1401,sizeof(gk_Index1401)/sizeof(gk_Index1401[0]), 0x1401},
  { (subindex*)gk_Index1402,sizeof(gk_Index1402)/sizeof(gk_Index1402[0]), 0x1402},
  { (subindex*)gk_Index1403,sizeof(gk_Index1403)/sizeof(gk_Index1403[0]), 0x1403},
  { (subindex*)gk_Index1600,sizeof(gk_Index1600)/sizeof(gk_Index1600[0]), 0x1600},
  { (subindex*)gk_Index1601,sizeof(gk_Index1601)/sizeof(gk_Index1601[0]), 0x1601},
  { (subindex*)gk_Index1602,sizeof(gk_Index1602)/sizeof(gk_Index1602[0]), 0x1602},
  { (subindex*)gk_Index1603,sizeof(gk_Index1603)/sizeof(gk_Index1603[0]), 0x1603},
  { (subindex*)gk_Index1800,sizeof(gk_Index1800)/sizeof(gk_Index1800[0]), 0x1800},
  { (subindex*)gk_Index1801,sizeof(gk_Index1801)/sizeof(gk_Index1801[0]), 0x1801},
  { (subindex*)gk_Index1802,sizeof(gk_Index1802)/sizeof(gk_Index1802[0]), 0x1802},
  { (subindex*)gk_Index1803,sizeof(gk_Index1803)/sizeof(gk_Index1803[0]), 0x1803},
  { (subindex*)gk_Index1A00,sizeof(gk_Index1A00)/sizeof(gk_Index1A00[0]), 0x1A00},
  { (subindex*)gk_Index1A01,sizeof(gk_Index1A01)/sizeof(gk_Index1A01[0]), 0x1A01},
  { (subindex*)gk_Index1A02,sizeof(gk_Index1A02)/sizeof(gk_Index1A02[0]), 0x1A02},
  { (subindex*)gk_Index1A03,sizeof(gk_Index1A03)/sizeof(gk_Index1A03[0]), 0x1A03},
  { (subindex*)gk_Index6005,sizeof(gk_Index6005)/sizeof(gk_Index6005[0]), 0x6005},
  { (subindex*)gk_Index6100,sizeof(gk_Index6100)/sizeof(gk_Index6100[0]), 0x6100},
  { (subindex*)gk_Index6102,sizeof(gk_Index6102)/sizeof(gk_Index6102[0]), 0x6102},
  { (subindex*)gk_Index6103,sizeof(gk_Index6103)/sizeof(gk_Index6103[0]), 0x6103},
  { (subindex*)gk_Index6106,sizeof(gk_Index6106)/sizeof(gk_Index6106[0]), 0x6106},
  { (subindex*)gk_Index6107,sizeof(gk_Index6107)/sizeof(gk_Index6107[0]), 0x6107},
  { (subindex*)gk_Index6108,sizeof(gk_Index6108)/sizeof(gk_Index6108[0]), 0x6108},
  { (subindex*)gk_Index6300,sizeof(gk_Index6300)/sizeof(gk_Index6300[0]), 0x6300},
  { (subindex*)gk_Index6302,sizeof(gk_Index6302)/sizeof(gk_Index6302[0]), 0x6302},
  { (subindex*)gk_Index6306,sizeof(gk_Index6306)/sizeof(gk_Index6306[0]), 0x6306},
  { (subindex*)gk_Index6307,sizeof(gk_Index6307)/sizeof(gk_Index6307[0]), 0x6307},
};

const indextable * gk_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;*callbacks = gk_Index1017_callbacks; break;
		case 0x1018: i = 3;break;
		case 0x1200: i = 4;break;
		case 0x1400: i = 5;break;
		case 0x1401: i = 6;break;
		case 0x1402: i = 7;break;
		case 0x1403: i = 8;break;
		case 0x1600: i = 9;break;
		case 0x1601: i = 10;break;
		case 0x1602: i = 11;break;
		case 0x1603: i = 12;break;
		case 0x1800: i = 13;*callbacks = gk_Index1800_callbacks; break;
		case 0x1801: i = 14;*callbacks = gk_Index1801_callbacks; break;
		case 0x1802: i = 15;*callbacks = gk_Index1802_callbacks; break;
		case 0x1803: i = 16;*callbacks = gk_Index1803_callbacks; break;
		case 0x1A00: i = 17;break;
		case 0x1A01: i = 18;break;
		case 0x1A02: i = 19;break;
		case 0x1A03: i = 20;break;
		case 0x6005: i = 21;break;
		case 0x6100: i = 22;break;
		case 0x6102: i = 23;break;
		case 0x6103: i = 24;break;
		case 0x6106: i = 25;break;
		case 0x6107: i = 26;break;
		case 0x6108: i = 27;break;
		case 0x6300: i = 28;break;
		case 0x6302: i = 29;break;
		case 0x6306: i = 30;break;
		case 0x6307: i = 31;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &gk_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status gk_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index gk_firstIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  5, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  13, /* PDO_TRS */
  17 /* PDO_TRS_MAP */
};

const quick_index gk_lastIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  16, /* PDO_TRS */
  20 /* PDO_TRS_MAP */
};

const UNS16 gk_ObjdictSize = sizeof(gk_objdict)/sizeof(gk_objdict[0]); 

CO_Data gk_Data = CANOPEN_NODE_DATA_INITIALIZER(gk);

