
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef GK_H
#define GK_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 gk_valueRangeTest (UNS8 typeValue, void * value);
const indextable * gk_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data gk_Data;
extern UNS8 Global_Interrupt_Enable_Digital;		/* Mapped at index 0x6005, subindex 0x00*/
extern UNS16 Read_Inputs_16_Bit[1];		/* Mapped at index 0x6100, subindex 0x01 - 0x01 */
extern UNS16 Polarity_Input_16_Bit[1];		/* Mapped at index 0x6102, subindex 0x01 - 0x01 */
extern UNS16 Filter_Constant_Input_16_Bit[1];		/* Mapped at index 0x6103, subindex 0x01 - 0x01 */
extern UNS16 Interrupt_Mask_Any_Change_16_Bit[1];		/* Mapped at index 0x6106, subindex 0x01 - 0x01 */
extern UNS16 Interrupt_Mask_Low_to_High_16_Bit[1];		/* Mapped at index 0x6107, subindex 0x01 - 0x01 */
extern UNS16 Interrupt_Mask_High_to_Low_16_Bit[1];		/* Mapped at index 0x6108, subindex 0x01 - 0x01 */
extern UNS16 Write_Outputs_16_Bit[1];		/* Mapped at index 0x6300, subindex 0x01 - 0x01 */
extern UNS16 Change_Polarity_Outputs_16_Bit[1];		/* Mapped at index 0x6302, subindex 0x01 - 0x01 */
extern UNS16 Error_Mode_Outputs_16_Bit[1];		/* Mapped at index 0x6306, subindex 0x01 - 0x01 */
extern UNS16 Error_Value_Outputs_16_Bit[1];		/* Mapped at index 0x6307, subindex 0x01 - 0x01 */

#endif // GK_H
